Array se similar a lista
1D -> SERIES
2D -> DATAFRAME

Un sataframe en Panda viene a ser como una hoja de Excel.

Tiene filas / Colunas y un Index para cada fila.

     idx   States    Population     Postal   -> Feactures (El nombre de la columna.)
     0     s1        123456789       CA   

     El nombre en cada fila se llama también Observación en este data frame hay 1 Observación y 3 Características
    
Traducción de la terminalogía entre excel y Pandas.
Excel                         Pandas
Hoja de cálculo                DataFrame
Columna                        Columna o Serie
Fila                           Fila
Números que indican la fila    index (índice)
Celda vacía                    NaN

COMO CREAR UN DATAFRAME
    COL1   COL2
0     1     4
1     2     5
2     3     6

1. Array o series con numpy Array
np.array([[1,4], [2,5], [3.6]])
Sin usar numpy
data = [[1,4], [2,5], [3.6]]

2. Diccionarios.
my_dict = {'key1':value1, 'key2':value2}   # Esto crear series (item in python) de 1D.
keyx -> Nombre columna
valuex -> dato

3. Archivo CSV.
Leer el contenido.

In [1]:
import pandas as pd
import numpy as np

1 CREANDO UN DATAFRAME USANDO ARRAYS

1.1 Opcion1 Arrays con numpy

In [2]:
#Creamos un Array con np.
data = np.array([[1,4], [2,5], [3,4]]) # cada conjunto es una fila.

In [5]:
#Crear un dataframe
df = pd.DataFrame(data, 
             index=['row1', 'row2', 'row3'],
             columns=['col1', 'col2'] )
df

      col1  col2
row1     1     4
row2     2     5
row3     3     4

1.2 Opcion1 Arrays sin numpy

In [6]:
# El array 
data = [[1,4], [2,5], [3,4]]

In [7]:
#Crear un dataframe
df = pd.DataFrame(data, 
             index=['row1', 'row2', 'row3'],
             columns=['col1', 'col2'] )
df

      col1  col2
row1     1     4
row2     2     5
row3     3     4

2 CREAR UN DATAFRAME USANDO DICCIONARIOS.

In [10]:
#Vamos a crear listar
states = ['Califormia', 'Texas', 'Florida', 'New York']
population  = [39613493, 29730311, 21944577, 19299981]

In [11]:
#Almacenamos las listas en un diccionario.
dict_tates = {'States':states, 'Popularion': population}

In [12]:
#Crear un dataframe
df = pd.DataFrame(dict_tates)
df

       States  Popularion
0  Califormia    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

3 Creando un dataframe con archivos csv

In [ ]:
#leyendo el archivo csv
df_exmans = pd.read_csv('StudentsPerformance.csv')  #Toda la información sería un DataSeet

In [ ]:
df_exmans  #En pandas DataSeet es un DataFrame

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

2. MOSTRAR UN DATAFRAME

In [16]:
import pandas as pd
df_exmans = pd.read_csv('StudentsPerformance.csv')
df_exmans

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [17]:
# Mostrar las 5 primera filas
df_exmans.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [18]:
# Mostrar las 5 ultimas filas
df_exmans.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [22]:
# Mostrar la n  filas.
df_exmans.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [ ]:
#Podemos decir que siempre muestre todas las filas.
pd.set_option('display.max_rows', 1000)
df_exmans

In [21]:
# acceder al traibuto shape para que nos digas el número de filas y columnas del dataframe
df_exmans.shape

(1000, 8)

ATRIBUTOS, METODOS Y FUNCIONAES DE PANDAS.

Atributo -> Valor asociado con un objeto (refernciado por nombre usando el punto ".")
df.columns
Función -> Grupo de sentencias relacionadas que hacen una tarea específica.
    max(), min(), len()..... funciones de python.
Métodos -> Una función que es definida dentro del cuerpo de una clase. df.head()

In [23]:
import pandas as pd
df_exmans = pd.read_csv('StudentsPerformance.csv')

In [ ]:
#Conocer el número de filas y columnas.
df_exmans.shape

(1000, 8)

In [ ]:
#obetener el acdeso al atributo index
df_exmans.index

RangeIndex(start=0, stop=1000, step=1)

In [27]:
# Obetner el acceso al atirbuto de la columnas.
df_exmans.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [28]:
# Obtener el tipo de dato de cada columna.
df_exmans.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

2 METODOS

In [29]:
# Mostrar las x primera filas
df_exmans.head(3)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93

In [31]:
# Obtener información del dataframe
df_exmans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [32]:
# Obtención de valores estadísticos del DF
df_exmans.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

3 FUNCIONES

In [33]:
# Longitud de un DF
len(df_exmans)

1000

In [ ]:
# Obetner el valor máximo  de valores númericos.  pero nos devuelve el valor ma´s grande del index.
max(df_exmans.index)

999

In [36]:
# Obetnemos el valor mínimo.
min(df_exmans.index)

0

In [37]:
#Obtenerl el tipo de dato
type(df_exmans)

pandas.core.frame.DataFrame

In [41]:
# Redondear valores del DF
pd.set_option('display.max_rows', 10) #Devolvemo el valor filas a cambiar a un valor normal que anets nos hemos pasado.
round(df_exmans, 2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

4 SELECCIONAR 1 COLUMNA EN UN DF

SELECCIONAR COLUMNA

METODO 1 SELECCION COLUMNA.

In [42]:
df_exmans["gender"]

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [43]:
type(df_exmans["gender"])

pandas.core.series.Series

In [45]:
df_exmans["gender"].index
df_exmans["gender"].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

METODO 2 SELECCION COLUMNA.

In [ ]:
df_exmans.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [49]:
#Si el nombre de la columna tiene varias palabras el más complejo porque no lo entiendo.
#df_exmans.math score
df_exmans.math_score

AttributeError: 'DataFrame' object has no attribute 'math_score'

In [50]:
df_exmans["math score"]

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

SELECCIONAR DOS O MAS COLUMNAS DE UN DF

In [54]:
df_exmans[["gender","math score"]]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [55]:
# REvisar el tipo de datos de esta selección
type(df_exmans[["gender","math score"]])

pandas.core.frame.DataFrame

In [57]:
# Seleccionar dos o mas columnas 
df_exmans[["gender", "writing score", "math score","reading score"]]

     gender  writing score  math score  reading score
0    female             74          72             72
1    female             88          69             90
2    female             93          90             95
3      male             44          47             57
4      male             75          76             78
..      ...            ...         ...            ...
995  female             95          88             99
996    male             55          62             55
997  female             65          59             71
998  female             77          68             78
999  female             86          77             86

[1000 rows x 4 columns]

AGREGAR UNA NUEVA COLUMNA A UN DF

In [58]:
import pandas as pd
df_exmans = pd.read_csv('StudentsPerformance.csv')
df_exmans

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

1 AGREGAR UNA NUEVA COLUMNA

1.1 AGREGAR UNA NUEVA COLUMNA CON UN VALOR.

In [ ]:
#Agregar una nueva columna al dataframe.
#seleccionamos una columna como si ya existiera
df_exmans["language score"] = 70
df_exmans

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

1.2 AGREGAR UNA NUEVA COLUMNA CON UN ARRAY.
El nuevo array tiene que tener el mismo número de filas que de columnas.

In [62]:
import numpy as np

In [64]:
# Creamos un array ficticio de 1000 elementos.
language_score = np.arange(0, 1000, 1)

In [65]:
#REvisamos el tamaño del array
len(language_score)

1000

In [66]:
# Agregamos una nueva columna al dataframe con un array.
df_exmans["language score"] = language_score
df_exmans

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [69]:
# Genermos el array con número aleatorios 
language_score = np.random.randint(1, 100, size=1000) #El segundo parámetros es exclusivo nunca saldrá 1000
len (language_score)

1000

In [71]:
df_exmans['language score'] = language_score
df_exmans

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,72
1,female,group C,some college,standard,completed,69,90,88,68
2,female,group B,master's degree,standard,none,90,95,93,49
3,male,group A,associate's degree,free/reduced,none,47,57,44,93
4,male,group C,some college,standard,none,76,78,75,76
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,84
996,male,group C,high school,free/reduced,none,62,55,55,19
997,female,group C,high school,free/reduced,completed,59,71,65,23
998,female,group D,some college,standard,completed,68,78,77,56
999,female,group D,some college,free/reduced,none,77,86,86,23

CREAR NUMERO DECIMALES ALEATORIOS ENTRE 1 Y 100 CON NP

In [72]:
np.random.uniform(1, 100, size=1000)

array([66.91177167, 29.65617684, 70.60447652, 66.1403882 , 31.37609548,
       73.52566964, 49.02094982, 35.36208259, 76.91490414, 50.09402331,
       15.83145692, 34.37247143,  5.20109436, 44.87127491, 56.72787641,
       72.77747468, 35.54111249, 30.90714195, 31.48629029, 84.17501222,
       47.69732986, 42.57388188, 88.59481089, 34.32523646, 65.577174  ,
       67.24013515, 76.93905353,  6.87372182, 66.3509343 , 71.8988937 ,
       84.41392946, 75.78526416, 98.90771261, 48.20058736, 77.68720689,
       32.13802866, 53.84290659, 34.0833561 , 27.25375387, 71.49658728,
       99.88506686, 72.4286604 , 68.30707489, 13.65977013,  9.52921849,
        9.51181068, 33.99650725, 72.6710103 , 37.5427681 , 52.31885474,
       41.53083267, 78.48064716, 67.58401065, 49.08766674, 52.01871895,
       38.10047567, 62.16321625,  4.21239606, 11.48280358, 40.76350767,
       76.55016571, 75.72562885, 58.14637355, 63.00920888, 25.22030416,
       41.14961461, 98.99574207, 96.10672019, 73.88067957, 64.44542443,
       35.66074868,  9.79381795, 70.5673762 , 60.67770304, 87.46887644,
       42.01059524, 45.59866349, 47.45047901,  5.30155628, 34.18667573,
       77.3232252 , 89.69666847, 46.39846876, 89.23987568, 16.82637352,
       40.33825495, 58.31299357, 98.90341975, 81.47966372, 90.19694473,
       28.56794707, 35.38629947, 89.11011312, 33.19293975, 68.99391578,
       28.28386635, 12.79529888, 57.7342497 , 14.76585866, 33.02615734,
       82.22138331, 73.52150431, 97.87094984, 66.7094505 , 40.24439113,
       44.25206214, 50.28589239, 80.8363401 ,  6.20757977, 70.46667828,
       44.11750476,  5.77477068, 14.42830947, 23.38262683, 71.56035107,
       55.25650629, 51.69475085, 44.83654479, 23.79235186, 43.84522583,
       81.21340147, 82.90729702, 37.62077901, 96.91168021, 82.14694795,
       42.50305448, 90.52386437, 36.01246255, 71.35073434, 31.76889063,
       44.10808126,  2.92001718,  2.1068431 ,  5.8446155 , 40.92253994,
       47.83941802, 25.34266368, 17.67007381, 19.26530269, 40.14816334,
       78.14341706, 59.7155142 , 13.01892719, 36.60258249, 15.52948184,
       78.21936542, 31.7631171 , 85.02765845, 39.12909849, 13.52981776,
       74.81897605, 19.7285693 , 21.36933361,  4.03338896, 19.05145844,
        5.32100374, 43.04947986,  5.80415054, 65.28046881, 30.11230069,
       92.81513557, 94.31473105, 99.29466742, 33.24320235, 38.18968169,
       94.13789256,  1.57216535, 36.78906312, 96.43965462, 17.12069957,
       91.77763522, 49.32120894, 18.66659509, 34.32132894, 39.99468799,
       24.41228186, 39.54587741, 16.36868455, 37.45886851, 88.67185894,
       81.27083459, 34.36406764, 55.92772296, 36.01436456, 84.35460054,
       19.38728433, 36.84070586, 95.62631771, 75.17653379, 55.90405125,
       15.5057991 , 49.02620775, 45.34843517, 93.93703731, 44.96089019,
       35.40753729, 26.93417695, 65.76852549, 52.38625202, 84.23702041,
       36.05164044, 24.5962487 , 61.8312014 , 76.44844349, 32.82847532,
       19.69703661, 81.43611579, 37.85018488, 48.74043675, 38.60182314,
        2.85161538, 17.50674772, 99.74192589, 40.16320495, 30.99670291,
       99.47265857, 99.56518848, 74.32280922, 86.45433818, 91.08091415,
       29.98000934, 53.99402189,  1.95866781,  7.66339737, 56.04907979,
       75.72811347, 52.36231988, 14.45975602,  5.02730947, 67.82070352,
       86.11380386,  8.32558367, 78.19587143, 54.57046473, 50.44811319,
       33.82912072, 83.92602659, 80.91215604, 31.6568414 , 37.9432626 ,
       24.09933074, 96.71263115, 79.83090179, 11.39703182, 69.20607245,
       48.07964261, 47.24787304, 87.74819515, 84.89125663,  8.58010022,
       81.69569105, 75.45100574, 66.83511332, 23.80387113, 85.41369278,
       23.33695494, 69.43299022,  5.2771923 , 85.34554403, 28.04262458,
       42.83995834, 84.82736724, 93.36470308, 47.20739908, 69.69060715,
       36.00898522, 88.52133161, 75.87174421, 89.4805704 , 23.9088603 ,
       11.25211642,  9.50077902, 35.20346413, 12.69434051, 89.60646441,
       21.48902968, 89.76002754, 92.89876218, 13.63450385, 16.86585093,
        4.33752496, 88.63427401, 86.15299092, 34.21761649, 28.75182214,
       64.34085243, 12.80822008, 10.7996947 , 39.10299604, 47.45490416,
       96.33584753, 85.73657473, 11.62179004, 65.1102373 , 34.78647764,
        7.03336908,  6.02374465,  6.064152  , 77.03972852, 61.14997523,
        9.3150666 , 86.16757471, 79.94892894,  3.27985231, 65.20607312,
        1.5355446 , 13.88893663, 32.25281392, 72.44274593, 28.99170395,
       68.42843469, 69.86468471, 31.10850838,  6.32970653, 66.69670823,
       61.12171861, 18.03024857, 74.58038966,  5.1034208 ,  2.64910731,
       96.89059013, 79.17742223, 33.81558498, 34.83762251, 87.07724998,
       23.69607335,  1.76031406, 41.88191841, 54.06908487,  7.1281514 ,
       22.90140943, 86.09587807,  4.35765727,  1.91003493, 90.76828007,
       87.24248805, 54.65484503, 47.81167597,  5.58839357, 83.15856238,
       84.64142182, 15.71983685, 92.09304772, 18.14689289, 62.39655097,
       39.34860367, 75.13278897, 66.38653395, 86.17857606, 34.75044216,
       92.07655349, 55.11116013, 79.45262633, 62.77859701, 78.33196361,
       23.41531764, 65.91840194, 62.93583987, 33.94382831, 69.85061598,
       95.92188795, 84.73314401, 19.55816813, 74.49407688, 23.57931965,
       12.32995087,  2.14118837, 52.15478674, 41.23346471, 12.70527152,
       14.77334124, 75.9290334 , 47.12965137,  4.30378171,  6.00781097,
       27.41681631, 86.57765815, 96.24127822, 66.24648256, 21.71800041,
       60.45961755, 15.50732389, 28.82767596, 77.25187454, 73.35732848,
       71.3423652 , 43.08417755, 37.91294502, 71.25243113, 37.33824065,
        5.84611878, 35.70640263, 69.44198361, 92.15917916, 68.23994596,
       14.79615222,  1.88331939, 51.7228258 , 24.27054139, 19.18938769,
       98.59024846, 95.49054954, 76.2728712 ,  6.68662106, 91.13395995,
        5.43038253, 92.34541298, 43.0742015 , 72.84263243, 45.64923912,
       39.69753453, 92.78530382, 19.32138871, 71.68206174, 92.20895428,
       71.14750822, 19.83566   , 21.01014404, 37.44782294, 55.88153102,
       97.097016  , 81.43846342, 72.12066427, 59.62477125, 16.52498832,
       82.91343847, 23.99751008, 56.17816283, 52.7757076 , 24.04756026,
       96.22540772, 22.21186393, 95.49603151, 88.68046427, 72.53534023,
       92.48971337, 46.19057144, 81.31962905, 17.90982431, 74.64931995,
        5.31653219, 10.02006605, 85.10908257, 47.51149042, 91.22266016,
       45.26172292, 71.33388575, 51.63150111, 95.86319933, 85.23004114,
       23.34250666, 77.40318663, 23.65940734, 17.27558697, 75.43365195,
       93.49039493, 77.12505532, 82.99165078, 22.3480977 , 44.2395228 ,
       95.16658173, 22.58398598, 18.99190651, 91.88082982, 67.00029441,
       15.69472742, 21.53504235, 74.94626224, 74.68907449, 54.45901907,
       42.14173007, 82.28299455, 88.33427141, 72.99668493, 54.93291072,
       67.50831557, 23.85545436, 37.50267731, 41.46479539, 36.08783223,
       53.31508439, 25.8649282 , 98.55204251, 90.5814903 , 96.76209081,
       78.41479157, 17.05349677, 27.80961164,  3.69431451,  9.94953109,
       54.5925397 ,  5.23790015, 46.91528335, 38.10338866, 14.55515732,
        1.198297  , 64.05538185, 10.86078448, 73.95522288, 64.99596891,
       74.38562301, 57.24849803, 73.88717521, 34.30940859, 77.91674993,
       40.19189795, 11.66814139, 14.47764509, 66.4921844 , 52.63385554,
       10.97731222, 59.33417141,  5.20096429, 17.13182213, 36.98878067,
        3.88566993, 89.95030635,  4.73360531, 37.16020606, 49.91576852,
       15.13189423, 77.20709251, 29.80401297, 74.87367371, 21.78791269,
       15.57001581, 21.75923186, 68.69817486, 73.5070407 , 37.47773518,
       61.20510888, 86.41550612, 62.91391576, 16.55519534, 88.97983774,
       97.06013271, 58.889461  , 61.97759951, 14.4114165 , 41.75164691,
       54.4110821 , 25.84427819, 72.73572312, 17.78024778, 48.03318518,
       50.56633732, 39.94723802, 96.17385093, 33.05815629, 52.45832516,
       60.11861866,  8.73585412, 56.26593283,  8.40274755, 37.45414956,
       15.42942732, 92.5462434 , 13.07329591, 67.8214195 ,  1.11862632,
       67.20251251, 72.33430174, 26.32380997, 64.33318825, 31.01695195,
       60.52973797, 42.32314861, 93.90001079, 59.78176701, 93.31282934,
       22.42162535, 62.5827181 , 35.19709101,  6.00641929,  8.08896117,
       93.69531681, 86.36501565, 26.89926791, 23.614726  , 62.19009559,
       62.50345085, 99.25041609, 28.30861787, 47.20689461, 80.26912593,
       77.59181399, 44.0006306 , 67.76884529, 31.17134082, 63.40390132,
       88.19884351, 13.07060211, 40.14738989, 30.37604386,  3.18880118,
       96.1855255 , 32.9217463 ,  7.99819761, 76.85606029, 12.93789276,
       97.28026191, 61.28000878, 53.05870661, 34.55443142, 60.46653385,
       23.11875291, 58.38216592, 39.27835362, 65.52377078,  5.25084816,
       31.88294302, 66.89899271, 31.33698256, 43.08349835, 94.92346334,
       44.74261801,  4.94204612, 60.58946763, 22.70892863, 40.56514167,
       68.0756873 , 79.92577395, 91.4965091 , 14.57809118,  2.90071828,
       93.30558741, 59.75181535, 31.73792158, 73.84621224, 24.21235624,
       92.29549317, 64.82304197, 68.00277559, 43.93133288, 20.12213296,
        8.68586287, 22.4750174 , 47.39457754, 12.08062556, 69.10285334,
       58.91148465, 30.81405521, 90.39421497, 77.58922282, 42.88850869,
        3.45933474, 30.35231791, 42.40126456, 20.61257507, 95.84490395,
       85.60706489, 56.63826635, 21.60157143, 62.94276566, 58.84861796,
       53.18860127, 87.53451786, 94.00482662, 18.95333544, 91.55390826,
       34.39221971, 63.75211104, 75.97034767, 88.60482896, 39.89749394,
       37.76106588, 98.03313843,  9.30604085, 10.32996003, 36.65693421,
       13.25419012, 43.06598089, 32.99390614, 13.43629898, 57.90497766,
       99.48996409, 51.62851253, 67.91775429, 11.65230322, 46.50213733,
       60.39655623, 28.21367763, 97.33062799, 82.01013618,  1.79047718,
       52.45968102,  1.06509774, 44.17349323, 68.61127177, 44.51912516,
       69.42201867, 59.36036456, 37.6859787 , 43.21840774, 93.66063963,
       42.01677523, 13.08306355, 84.82540756,  4.07376308, 88.22370601,
       68.17102776, 49.42400117, 96.34815138, 28.76840277, 82.70552648,
       70.67620586, 42.3028976 , 20.32630667, 44.43826499, 75.87262737,
       80.58004588, 75.09172228, 24.57102851, 49.98195896, 15.69513198,
        3.66143556, 99.20401997, 15.82136666, 45.529984  , 89.41180906,
       27.35318751, 85.46930093, 27.01435306, 30.27765757, 69.14179539,
       96.93874245, 45.77007728, 21.46854359, 36.08076267, 68.21370131,
       84.94633192, 85.81772549, 86.10703616, 91.8341142 , 35.87584388,
       68.54445385, 57.44614615, 99.74747885, 39.08086886, 48.98914488,
       68.88154281, 53.26352522, 99.74298362, 99.21629566, 49.94250006,
       45.90663364, 81.51546156, 39.5494286 , 82.33825687, 77.12679158,
       46.66663087, 98.81097967, 73.78463003, 54.48349916, 33.85025446,
       90.89403229, 85.37971226,  4.32534736, 30.848495  , 46.99223199,
       23.5350235 , 52.81486835, 99.21867576, 59.53601475, 88.68564964,
       94.3603191 , 23.49741042,  5.4656665 , 27.53373703, 30.19136511,
       53.65029867, 62.96652928, 48.61831196, 49.72261533, 59.30962612,
       51.26359723, 29.9271363 , 99.62519523, 41.49171308, 38.12182027,
       82.88778758, 90.35402737, 78.43021176, 39.21696629, 57.83772069,
       84.34678111, 64.66620182, 79.95915752, 79.66976785, 93.5360722 ,
       58.50017095, 18.37112568, 32.43673038, 65.52212009, 21.55904325,
       37.96907073, 11.82171434, 81.51928721, 36.2626169 , 54.75321899,
       14.09864019, 86.71004916, 76.83811998, 94.6082689 , 69.63867981,
       66.58439045, 30.36880775, 89.44241466, 44.367551  , 96.88289179,
       75.73799191, 60.60569648, 60.82797496, 19.1840837 , 67.51398609,
       90.98766038, 87.0850524 , 88.0609465 ,  5.96724551,  1.62452725,
        3.55719893, 20.82052653, 15.22183083, 97.32128575, 97.57132976,
       66.72960483, 39.73211307, 82.03028437, 29.3653473 , 47.8121222 ,
       29.06599255, 87.47008762, 34.09212914, 84.76003112, 83.67020893,
       49.57479654, 94.32439939, 75.30191325, 28.32341489, 18.12008249,
       38.98755356, 71.56623199, 42.21367273, 29.89028449, 85.39559113,
       17.69989961, 45.68090799, 19.17027967, 19.34503888, 89.20619557,
       87.07824536, 76.65894356, 31.37200133, 77.97085895, 18.24090229,
       82.71426395, 27.95848434, 78.55104179, 57.18614345, 73.13542479,
        9.687045  , 94.03571427, 38.50123505, 10.44526131, 94.68877359,
        9.04889253,  6.36670252, 87.9992157 , 45.81099151, 30.0662358 ,
       43.84698541, 21.95351678, 92.17993115, 21.97660218, 53.66350764,
       99.60228555, 75.90794231, 86.95990249, 87.30860337, 98.02520265,
       34.0658518 , 20.32708278, 71.55528895, 37.25058204, 48.34004697,
       41.63195772, 81.89373379, 54.01056462, 70.62971244, 11.23137884,
       13.02146906, 45.49349659, 59.9578336 , 96.36332641, 25.14260234,
       22.49875864, 70.04556439, 49.93569511, 40.88981481, 54.68478104,
       15.82338174,  9.06815702, 54.55559741, 22.32274512, 93.6511675 ,
       23.62401259, 41.45576293, 74.02085409, 82.01801147, 74.61567151,
       42.86331454,  3.15238311, 31.50191121,  8.48371159, 69.108853  ,
       26.19962452, 70.44295098, 10.23512748, 92.93459063,  3.71690656,
       25.61092851, 20.6863271 , 59.29879834, 60.26243554,  5.37376479,
       51.40199465, 51.62359545, 99.42795349, 21.12904129, 72.93816485,
       82.41831678, 85.12381554, 94.30852439, 13.0263412 , 91.58302487,
       64.25860886, 67.08530704, 97.03054725, 70.47439724, 92.60853809,
       98.14609817, 37.509334  , 61.74741762, 20.91240684, 70.83850666,
       60.45328496, 75.58306454, 31.52716829, 28.87778008,  3.53205851,
       84.41918071, 67.27670085, 20.67593462, 78.78690648, 56.30013509,
       87.77645391, 36.9330563 , 42.67356106, 47.31375812, 77.44826293,
       58.64075088, 15.73538514, 84.28216516, 62.20783935, 57.6853455 ,
       92.30768919, 27.87612787,  1.37430014,  8.17939506, 58.1816264 ,
       28.91090658, 61.28255023,  7.61733636, 29.70687178, 72.57630125,
       82.04524782, 95.69546997, 45.18174618,  3.28309795, 27.96253412,
       74.41991381, 68.00404863, 89.87803582, 94.71353218, 48.21165678,
       53.16467474, 69.18926234, 72.07023452, 70.15263539, 55.70301654,
       25.52918554, 58.97282612,  2.42519774, 41.079377  ,  6.57305699,
       77.53789799, 54.07103327, 14.57073218, 34.6216845 , 64.88954376])

OPERACIONES EN DATAFRAME